#! /usr/bin/env node

'use strict';

const fs = require('fs');
const checkMsg = require('../../scripts/git-validations');
const msgFile = process.argv[2];

let isValid = true;

if (msgFile) {
    const commitMsg = fs.readFileSync(msgFile, {encoding: 'utf-8'});
    const firstLine = commitMsg.split('\n')[0];
    isValid = checkMsg(firstLine);

    if (!isValid) {
        console.error('\nRead more about commit message at [add your link here]');
    }
}

process.exit(isValid ? 0 : 1);