#! /usr/bin/env node

'use strict';

const fs = require('fs');
const gitScript = require('../../scripts/git-script');
const msgFile = process.argv[2];

let isValid = true;

if (msgFile) {
    const commitMsg = fs.readFileSync(msgFile, {encoding: 'utf-8'});
    const firstLine = commitMsg.split('\n')[0];
    isValid = gitScript.validateCommit(firstLine);
}

process.exit(isValid ? 0 : 1);